
name: Publish pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: yarn
    - run: yarn build
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        rm -rf docs
        mv build docs
        touch docs/.nojekyll
        git add -f docs
        git commit -m "built for github pages"
        git push
